trigger:
- main

pool:
  vmImage: 'ubuntu-latest'   # Using the latest Ubuntu agent

stages:
  # Stage 1: Set Java Version and Build
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Compile with Maven'
        steps:
        - task: JavaToolInstaller@0
          inputs:
            versionSpec: '17'
            jdkArchitectureOption: 'x64'
            cleanDestinationDirectory: true
          
          # Step 2: Maven build
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean install'
            publishJUnitResults: false
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
