trigger:
- main

pool:
  vmImage: 'ubuntu-latest'   # Using the latest Ubuntu agent

stages:
  # Stage 1: Set Java Version and Build
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Compile with Maven'
        steps:
          
            # - task: UseJavaVersion@1
            #   inputs:
            #   versionSpec: '17'   # Set the Java version to 17
            #   jdkArchitectureOption: 'x64'   # Use 64-bit architecture
            #   jdkSourceOption: 'PreInstalled'   # Specify to use pre-installed JDK

        - task: JavaToolInstaller@0
          inputs:
            versionSpec: '17'
            jdkArchitectureOption: 'x64'
            cleanDestinationDirectory: true
            jdkSourceOption: 'PreInstalled'
          
          # Step 2: Maven build
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'Package'
            publishJUnitResults: false
            codeCoverageToolOption: 'Cobertura'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
          
        # - task: CopyFiles@2
        #   inputs:
        #     Contents: '**/.jar'
        #     TargetFolder: '$(build.artifactstagingdirectory)'

        # - task: PublishBuildArtifacts@1
        #   inputs:
        #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        #     ArtifactName: 'drop'
        #     publishLocation: 'Container'
          
